-   id: dialplan-check
    name: asterisklint
    description: ''
    entry: asterisklint dialplan-check
    language: python
    'files': extensions.conf$
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
