-   id: dialplan-check
    name: dialplan-check
    description: 'Run asterisklint dialplan-check on extensions.conf files'
    entry: asterisklint dialplan-check
    language: python
    files: extensions\.conf$
    minimum_pre_commit_version: '2.9.2'
    types: [text]
