-   id: dialplan-check
    name: dialplan-check
    description: 'Run asterisklint dialplan-check on extensions.conf files'
    entry: asterisklint dialplan-check
    language: python
    'types': [text]
    files: extensions\.conf$
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
