name: main
on:
  push:
    branches:
    - develop
  schedule:
  - cron: '40 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install pre-commit-mirror-maker
    - run: git config --global user.name 'github-actions[bot]'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: pre-commit-mirror . --language python --package-name asterisklint --files-regex extensions\.conf$ --id dialplan-check --entry 'asterisklint dialplan-check'
    - run: |
        NEW_VER=$(cat .version)
        NEW_TAG=$(git describe --tags --always)
        echo "NEW_VER=$NEW_VER" >> $GITHUB_ENV
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo ${{ env.NEW_VER }}
        echo ${{ env.NEW_TAG }}
    - run: |
        git tag --delete ${{ env.NEW_TAG }}
        git reset --soft  HEAD~1
        git restore --staged .pre-commit-hooks.yaml
        git commit -m 'Mirror: ${{ env.NEW_VER }}'
        git tag ${{ env.NEW_TAG }}
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:refs/heads/develop --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: v${{ env.NEW_VER }} == ${{ env.NEW_TAG }}
