name: Mirror

on:
  workflow_dispatch:
  push:
    branches:
    - master
  schedule:
  - cron: '40 8 * * *'

permissions:
  contents: write

jobs:
  mirror:
    name: main
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Get latest asterisklint version
      id: get_version
      run: |
        UP_VER=$(curl -L -s "https://pypi.org/pypi/asterisklint/json" | jq  -r '.releases | keys | .[]' | sort -Vr | head -n 1)
        echo "UP_VER=$UP_VER" >> $GITHUB_ENV
        echo "asterisklint: $UP_VER"

    - run: git config --global user.name 'github-actions[bot]'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Set current version
      run: |
        CUR_VER=$(cat version.txt)
        echo "CUR_VER=$CUR_VER" >> $GITHUB_ENV
        echo "current: $CUR_VER"
        echo "upstream: $UP_VER"

    - run: |
        if [ "$NEW" != "$OLD" ]
        then
            echo "$NEW" > version.txt
            git add version.txt
            git commit -m "Mirror: ${{ steps.get_version.outputs.latestVersion }}"
            git tag v${{ env.UP_VER }}
            git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
            git push origin HEAD:refs/heads/master --tags
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW: ${{ env.UP_VER }}
        OLD: ${{ env.CUR_VER }}
