name: main
on:
  push:
    branches:
    - develop
  schedule:
  - cron: '40 8 * * *'

jobs:
  mirror:
    name: main
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: Bruce17/ghaction-package-latest-version@v1.1.2
      id: get_version
      with:
        package: asterisklint
        language: python

    - run: git config --global user.name 'github-actions[bot]'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Set current version
      run: |
        CUR_VER=$(cat version.txt)
        echo "CUR_VER=$CUR_VER" >> $GITHUB_ENV
        echo "$CUR_VER"
        echo ${{ steps.get_version.outputs.latestVersion }}

    - run: |
        if [ "$NEW" != "$OLD" ]
        then
            echo "$NEW" > version.txt
            git add version.txt
            git commit -m 'Mirror: $NEW'
            git tag v$NEW
            git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
            git push origin HEAD:refs/heads/develop --tags
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW: ${{ steps.get_version.outputs.latestVersion }}
        OLD: ${{ env.CUR_VER }}
